markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
name: index
title: Blog & Projects
url: https://clarkadisney.github.io
plugins: [jekyll-paginate]
paginate: 5
paginate_path: /page:num/
categories: 