markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
name: Archive
title: Blog & Archive
url: https://clarkadisney.github.io
plugins: [jekyll-paginate, jekyll-admin]
paginate: 5
paginate_path: /page:num/
categories: 