markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
name: Archive
title: Blog & Archive
url: https://clarkadisney.github.io
plugins: [jekyll-paginate, jekyll-admin]
paginate: 3
paginate_path: recent/page:num/
categories: 